export const USER_LOGGED_IN ='USER_LOGGED_IN'
export const USER_LOGGED_OUT ='USER_LOGGED_OUT'
export const GET_LOGGED_USER = 'GET_LOGGED_USER'
//feeds stuff
export const GET_ALL_FEEDS = 'GET_ALL_FEEDS'
//gif stuffs
export const POST_GIFS = 'POST_GIFS'
export const GET_ALL_GIFS = 'GET_ALL_GIFS'
export const GET_SINGLE_GIFS = 'GET_SINGLE_GIFS'
export const DELETE_GIFS = 'DELETE_GIFS'
export const POST_GIF_COMMENT ='POST_GIF_COMMENT';
//articles stuffs
export const POST_ARTICLES = 'POST_ARTICLES';
export const EDIT_ARTICLES = 'EDIT_ARTICLES'
export const GET_SINGLE_ARTICLES = 'GET_SINGLE_ARTICLES'
export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES'
export const GET_CAT_ARTICLES = 'GET_CAT_ARTICLES'
export const POST_ARTICLE_COMMENT = 'POST_ARTICLE_COMMENT'
export const DELETE_ARTICLES = 'DELETE_ARTICLES';
//categories stuff
export const POST_CATEGORIES ='POST_CATEGORIES';
export const EDIT_CATEGORIES = 'EDIT_CATEGORIES'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_SINGLE_CATEGORIES = 'GET_SINGLE_CATEGORIES'
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES'
export const GET_USER_ARTICLES = 'GET_USER_ARTICLES'